In [28]:
import numpy as np
import math
import time

In [41]:
n =100

limit = 0.96
update = n/10
for i in range(n):
    print(round(0.96 - i*step,2))



0.96
0.96
0.95
0.95
0.94
0.94
0.94
0.93
0.93
0.92
0.92
0.92
0.91
0.91
0.9
0.9
0.9
0.89
0.89
0.88
0.88
0.88
0.87
0.87
0.86
0.86
0.86
0.85
0.85
0.84
0.84
0.84
0.83
0.83
0.82
0.82
0.82
0.81
0.81
0.8
0.8
0.8
0.79
0.79
0.78
0.78
0.78
0.77
0.77
0.76
0.76
0.76
0.75
0.75
0.74
0.74
0.74
0.73
0.73
0.72
0.72
0.72
0.71
0.71
0.7
0.7
0.7
0.69
0.69
0.68
0.68
0.68
0.67
0.67
0.66
0.66
0.66
0.65
0.65
0.64
0.64
0.64
0.63
0.63
0.62
0.62
0.62
0.61
0.61
0.6
0.6
0.6
0.59
0.59
0.58
0.58
0.58
0.57
0.57
0.56


In [55]:
a = np.ones(10)
b = np.ones(10)
a=10
b=10
np.random.beta(a,b,20)
print(x)

[0.28817869 0.5229472  0.36388734 0.58589813 0.64081429 0.46733797
 0.50021669 0.24007433 0.52804706 0.56809847 0.38593655 0.28098267
 0.35850218 0.43020765 0.52256014 0.40520266 0.44552844 0.42467713
 0.39426406 0.43724752]


In [40]:
a = np.array([1, 2 ,3])
print(type(a))
a = a.tolist()
print(type(a))

<class 'numpy.ndarray'>
<class 'list'>


In [93]:
a = np.array([4,10,5,9,2,1,6])

k =3
x = np.argpartition(a,5)
print(x)
print(a[x])

import numpy as np
arr = np.array([1, 3, 2, 4, 5])
arr.argsort()[-k:][::-1]

[4 0 2 5 6 3 1]
[ 2  4  5  1  6  9 10]


array([4, 3, 1])

In [119]:
a = np.array([2,3,1])
b = np.array([2,2,3])

x = 12
a = np.append(a,10)
print(a)
if x in a:
    print("test")
    i = np.where(a==x)
    print(i)
    b[i]+=1
    print(b[i])


[ 2  3  1 10]


In [72]:
def kl(x,y):
    if x==0:
        kl_value = -math.log((1-y))
        return kl_value
    if x==1:
        kl_value = -math.log(y)
        return kl_value
    else:
        ln1 = math.log(x/y)
        ln2 = math.log((1-x)/(1-y))
        kl_value = x * ln1 + (1-x) * ln2 
        return kl_value


def bs(p_,start,end,kl_p_q):
    middle = (start + end)/2
    kl_p_m = kl(p_,middle)
    #print(middle)

    #return 0.5
    while(abs(kl_p_m-kl_p_q) > 0.0001 and abs(start-end) > 0.0001): 
        #print(kl_p_m , kl_p_q)
        if(kl_p_m > kl_p_q ):
            end = middle
        else:
            start = middle
        middle = (start + end)/2
        kl_p_m = kl(p_,middle)
        
    return middle
        
        

In [73]:
def bs2(p_,start,end,kl_p_q):
    middle = (start + end)/2
    #print(middle)
    kl_p_m = kl(p_,middle)
    #print(kl_p_m , kl_p_q)
    #return 0.5
    if abs(kl_p_m-kl_p_q) < 0.0001:
        #print(middle)
        return middle
    elif(kl_p_m > kl_p_q ):
        return bs(p_,start,middle,kl_p_q)
    else:
        return bs(p_,middle,end,kl_p_q)

In [74]:

ln_t = math.log(500)
lnln_t = math.log(ln_t)
c = 3
ln_final = (ln_t + c * lnln_t)
q = 0.999

kl_p_q = ln_final / 20


tic = time.time()
for i in range(10000):
    x = bs(0.7,0.7,q,kl_p_q)
toc = time.time()

print(toc-tic)


tic =time.time()
for i in range(10000):
    y = bs2(0.7,0.7,q,kl_p_q)
toc = time.time()

print(toc-tic)

print(x,y)

        
        # END EDITING HERE

0.12114524841308594
0.08352518081665039
0.9805679931640624 0.9805679931640624


In [20]:
arm = np.array([4,5,6])
arm=np.delete(arm,np.where(arm==6))
print(arm)

[4 5]


In [ ]:
dect

In [4]:
class Algorithm:
    def __init__(self, num_arms, horizon):
        self.num_arms = num_arms
        self.horizon = horizon
    
    def give_pull(self):
        raise NotImplementedError
    
    def get_reward(self, arm_index, reward):
        raise NotImplementedError

In [98]:
horizon = 100
num_arms = 2
prob = [0.4,0.7]
np.random.seed(0)

In [99]:
ucb = UCB(num_arms,horizon)
for i in range(10):
    x  = ucb.give_pull()
    if np.random.uniform(0,1)<prob[x]:
        rew =1
    else:
        rew =0
        
    ucb.get_reward(x,rew)
    #print(x)

arm : 0 rew : 0 mean: [0. 0.] ucb : [0. 0.] 
arm : 1 rew : 0 mean: [0. 0.] ucb : [1. 0.] 
arm : 0 rew : 0 mean: [0. 0.] ucb : [1. 1.] 
check
arm : 1 rew : 1 mean: [0.  0.5] ucb : [2. 1.] 
check
arm : 1 rew : 1 mean: [0.         0.66666667] ucb : [2. 2.] 
check
arm : 1 rew : 1 mean: [0.   0.75] ucb : [2. 3.] 
check
arm : 1 rew : 1 mean: [0.  0.8] ucb : [2. 4.] 
check
arm : 1 rew : 0 mean: [0.         0.66666667] ucb : [2. 5.] 
check
arm : 1 rew : 0 mean: [0.         0.57142857] ucb : [2. 6.] 
check
arm : 0 rew : 1 mean: [0.33333333 0.57142857] ucb : [2. 7.] 
check


In [112]:
class Thompson_Sampling(Algorithm):
    def __init__(self, num_arms, horizon):
        super().__init__(num_arms, horizon)
        # You can add any other variables you need here
        # START EDITING HERE
        #num_arms no. of arms
        #success no. of success of each arm
        self.success = np.zeros(num_arms)
        #no. of pull of each arm
        self.counts = np.zeros(num_arms)
        # END EDITING HERE
    
    def give_pull(self):
        # START EDITING HERE
        np.random.seed(0)
        #sample : array to store sample value from beta distribution
        sample = np.zeros(self.num_arms)
        #arm : index sarting from zero
        # for every arm a draw as sample from beta
        for arm in range(self.num_arms):
            sample[arm]=np.random.beta(self.success[arm]+1,self.counts[arm]-self.success[arm]+1)
        return np.argmax(sample)
        
        # END EDITING HERE
    
    def get_reward(self, arm_index, reward):
        # START EDITING HERE
        self.counts[arm_index]+=1
        if reward==1:
            self.success[arm_index]+=1
        print("arm : {} rew : {} success: {} count : {} ".format(arm_index,reward,self.success, self.counts))

        # END EDITING HERE

In [111]:
ucb = Thompson_Sampling(num_arms,horizon)
for i in range(10):
    x  = ucb.give_pull()
    if np.random.uniform(0,1)<prob[x]:
        rew =1
    else:
        rew =0
        
    ucb.get_reward(x,rew)

arm : 0 rew : 0 success: [0. 0.] ucb : [1. 0.] 
arm : 1 rew : 1 success: [0. 1.] ucb : [1. 1.] 
arm : 1 rew : 1 success: [0. 2.] ucb : [1. 2.] 
arm : 1 rew : 1 success: [0. 3.] ucb : [1. 3.] 
arm : 1 rew : 1 success: [0. 4.] ucb : [1. 4.] 
arm : 1 rew : 1 success: [0. 5.] ucb : [1. 5.] 
arm : 1 rew : 1 success: [0. 6.] ucb : [1. 6.] 
arm : 1 rew : 1 success: [0. 7.] ucb : [1. 7.] 
arm : 1 rew : 1 success: [0. 8.] ucb : [1. 8.] 
arm : 1 rew : 1 success: [0. 9.] ucb : [1. 9.] 


In [101]:
print(np.random.random())
print(np.random.randint(10))

0.7917250380826646
7


In [ ]:

# Example implementation of Epsilon Greedy algorithm
class Eps_Greedy(Algorithm):
    def __init__(self, num_arms, horizon):
        super().__init__(num_arms, horizon)
        # Extra member variables to keep track of the state
        self.eps = 0.1
        self.counts = np.zeros(num_arms)
        self.values = np.zeros(num_arms)
    
    def give_pull(self):
        if np.random.random() < self.eps:
            return np.random.randint(self.num_arms)
        else:
            return np.argmax(self.values)
    
    def get_reward(self, arm_index, reward):
        self.counts[arm_index] += 1
        n = self.counts[arm_index]
        value = self.values[arm_index]
        new_value = ((n - 1) / n) * value + (1 / n) * reward
        self.values[arm_index] = new_value


# START EDITING HERE
# You can use this space to define any helper functions that you need
# END EDITING HERE

class UCB(Algorithm):
    def __init__(self, num_arms, horizon):
        super().__init__(num_arms, horizon)
        # You can add any other variables you need here
        # START EDITING HERE

        #num_arms no. of arms
        # ucb : ucb values of each arm
        self.ucb = np.zeros(num_arms)
        #counts : no. of pull of each arm
        self.counts = np.zeros(num_arms)
        # mean : empirical mean
        self.mean = np.zeros(num_arms)
        self.h = 0
        # END EDITING HERE
        # END EDITING HERE
    
    def give_pull(self):
        # START EDITING HERE
        #print(self.h)
        if (self.h < self.num_arms):
            return self.h
        return np.argmax(self.ucb)
        # END EDITING HERE
    
    def get_reward(self, arm_index, reward):
        # START EDITING HERE

        # empirical means of arm_index    
        p_ = self.mean[arm_index]
        u = self.counts[arm_index]
        self.mean[arm_index]= (p_ * u + reward ) / (u+1) 

        #print(self.mean)

        self.counts[arm_index]+=1
        self.h+=1

        if (self.h >= self.num_arms):
            ln = math.log(self.h)
            for arm in range(self.num_arms):
                add_to_mean = math.sqrt((2*ln)/self.counts[arm])
                self.ucb[arm]= self.mean[arm_index] + add_to_mean
        # END EDITING HERE

class KL_UCB(Algorithm):
    def __init__(self, num_arms, horizon):
        super().__init__(num_arms, horizon)
        # You can add any other variables you need here
        # START EDITING HERE
        #num_arms no. of arms

        self.ucb = np.zeros(num_arms)
        #no. of pull of each arm
        self.counts = np.zeros(num_arms)
        # END EDITING HERE
    
    def give_pull(self):
        # START EDITING HERE
        return 0
        # END EDITING HERE
    
    def get_reward(self, arm_index, reward):
        # START EDITING HERE
        pass
        # END EDITING HERE


class Thompson_Sampling(Algorithm):
    def __init__(self, num_arms, horizon):
        super().__init__(num_arms, horizon)
        # You can add any other variables you need here
        # START EDITING HERE
        #num_arms no. of arms
        #success no. of success of each arm
        self.success = np.zeros(num_arms)
        #no. of pull of each arm
        self.counts = np.zeros(num_arms)
        # END EDITING HERE
    
    def give_pull(self):
        # START EDITING HERE
        np.random.seed(0)
        #sample : array to store sample value from beta distribution
        sample = np.zeros(self.num_arms)
        #arm : index sarting from zero
        # for every arm a draw as sample from beta
        for arm in range(self.num_arms):
            sample[arm]=np.random.beta(self.success[arm]+1,self.counts[arm]-self.success[arm]+1)
        return np.argmax(sample)
        # END EDITING HERE
    
    def get_reward(self, arm_index, reward):
        # START EDITING HERE
        self.counts[arm_index]+=1
        if reward==1:
            self.success[arm_index]+=1

        # END EDITING HERE


In [41]:
import time
tic = time.time()
np.random.beta(np.ones(100000),np.ones(100000))

print(time.time()-tic)


0.044472694396972656


In [42]:
tic = time.time()
for i in range(100000):
    np.random.beta(1,1)
    
print(time.time()-tic)

0.12258410453796387
